# CodeRabbit Configuration
# This file configures CodeRabbit's behavior for code reviews
# Install CodeRabbit from: https://github.com/apps/coderabbitai

language: javascript

# Review settings
reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  
  # Path-based instructions
  path_instructions:
    - path: "src/**/*.{js,jsx}"
      instructions: "Review React.js and JavaScript code for best practices. Check for security vulnerabilities, proper error handling, and code quality."

# Paths to exclude from review
paths:
  exclude:
    - "node_modules/**"
    - "dist/**"
    - "*.lock"
    - "package-lock.json"

